"""empty message

Revision ID: e3e01226a4f2
Revises: 3f3349dbef26
Create Date: 2024-10-08 16:05:17.264002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e01226a4f2'
down_revision = '3f3349dbef26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_userid_users'), 'users', ['userid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_userid_users'), type_='foreignkey')
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
